---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anything-llm-server-storage
  labels:
    app: anything-llm-fips
    app.kubernetes.io/name: anything-llm-fips
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anything-llm-collector-hotdir
  labels:
    app: anything-llm-fips
    app.kubernetes.io/name: anything-llm-fips
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anything-llm-collector-outputs
  labels:
    app: anything-llm-fips
    app.kubernetes.io/name: anything-llm-fips
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
